import type { GhostTape } from './types';

/** iOS에 포함된 기본 고스트와 같은 기보. 첫 실행에도 상대가 존재하도록 번들한다. */
export const BUILT_IN_GHOSTS: GhostTape[] = [
  {
    id: '469EF43E-B23A-4724-B6CD-65747D1749D1',
    ownerName: '새벽',
    ownerRating: 1180,
    side: 'BLACK',
    moves: [
      { kind: 'MOVE', from: { r: 8, c: 4 }, to: { r: 7, c: 4 } },
      { kind: 'PLACE', to: { r: 6, c: 4 } },
      { kind: 'MOVE', from: { r: 7, c: 4 }, to: { r: 6, c: 3 } },
      { kind: 'MOVE', from: { r: 6, c: 3 }, to: { r: 5, c: 2 } },
      { kind: 'MOVE', from: { r: 5, c: 2 }, to: { r: 4, c: 2 } },
      { kind: 'MOVE', from: { r: 4, c: 2 }, to: { r: 3, c: 2 } },
      { kind: 'MOVE', from: { r: 3, c: 2 }, to: { r: 2, c: 1 } },
      { kind: 'MOVE', from: { r: 2, c: 1 }, to: { r: 1, c: 2 } },
      { kind: 'MOVE', from: { r: 1, c: 2 }, to: { r: 0, c: 3 } },
    ],
    result: { winner: 'BLACK', reason: 'goal' },
    plyCount: 17,
    createdAt: '2026-08-17T04:25:26Z',
    source: 'seed',
    note: '선공으로 왕을 밀어 올린 기본 기보',
  },
  {
    id: '294A3433-277D-4187-A14C-F6A82406132A',
    ownerName: '이슬',
    ownerRating: 1260,
    side: 'WHITE',
    moves: [
      { kind: 'MOVE', from: { r: 0, c: 4 }, to: { r: 1, c: 3 } },
      { kind: 'MOVE', from: { r: 1, c: 3 }, to: { r: 2, c: 3 } },
      { kind: 'MOVE', from: { r: 2, c: 3 }, to: { r: 3, c: 4 } },
      { kind: 'MOVE', from: { r: 3, c: 4 }, to: { r: 4, c: 5 } },
      { kind: 'PLACE', to: { r: 4, c: 6 } },
      { kind: 'PLACE', to: { r: 3, c: 6 } },
      { kind: 'MOVE', from: { r: 4, c: 5 }, to: { r: 5, c: 4 } },
      { kind: 'MOVE', from: { r: 5, c: 4 }, to: { r: 6, c: 4 } },
      { kind: 'MOVE', from: { r: 6, c: 4 }, to: { r: 7, c: 5 } },
      { kind: 'MOVE', from: { r: 7, c: 5 }, to: { r: 8, c: 5 } },
    ],
    result: { winner: 'WHITE', reason: 'goal' },
    plyCount: 20,
    createdAt: '2026-08-17T04:25:31Z',
    source: 'seed',
    note: '후공으로 호위를 붙여 막아 낸 기보',
  },
  {
    id: '3FA39A5C-3C9F-46FC-933F-85452F559397',
    ownerName: '단풍',
    ownerRating: 1340,
    side: 'BLACK',
    moves: [
      { kind: 'PLACE', to: { r: 7, c: 4 } },
      { kind: 'PLACE', to: { r: 7, c: 5 } },
      { kind: 'MOVE', from: { r: 7, c: 5 }, to: { r: 7, c: 6 } },
      { kind: 'PLACE', to: { r: 7, c: 5 } },
      { kind: 'MOVE', from: { r: 7, c: 4 }, to: { r: 7, c: 3 } },
      { kind: 'MOVE', from: { r: 8, c: 4 }, to: { r: 7, c: 4 } },
      { kind: 'MOVE', from: { r: 7, c: 4 }, to: { r: 6, c: 3 } },
      { kind: 'MOVE', from: { r: 6, c: 3 }, to: { r: 5, c: 3 } },
      { kind: 'MOVE', from: { r: 7, c: 3 }, to: { r: 7, c: 2 } },
      { kind: 'MOVE', from: { r: 5, c: 3 }, to: { r: 4, c: 3 } },
      { kind: 'MOVE', from: { r: 4, c: 3 }, to: { r: 3, c: 2 } },
      { kind: 'PLACE', to: { r: 7, c: 1 } },
      { kind: 'MOVE', from: { r: 7, c: 1 }, to: { r: 8, c: 1 } },
    ],
    result: { winner: 'BLACK', reason: 'capture' },
    plyCount: 25,
    createdAt: '2026-08-17T04:25:44Z',
    source: 'seed',
    note: '서로 왕을 겨룬 균형 기보',
  },
];
